[package]
name = "differ"
version = "0.1.0"
edition = "2021"
description = "This program helps you to create a diff of two files or to apply an existing patch to a file."

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
miniz_oxide = "0.8.3"
rand = "0.8.5"
